### PR TITLE
Copied backend files from frontend repo

### PR DESCRIPTION
**Pull request by JoeDodgson**
## Changes made
* Copied all backend files from the engineer-app repo 

## Reviewer needs to check
* All files have been copied correctly
* Do not need to check the content of these files for the time being

### CODE REVIEW

**Review by niroshanwitharana — APPROVED** [review]
reviewed before approved. Two properties are missing in UserSchema. company and job title, hope Ian will update it as soon as he can.

**Comment by abc-1211** [comment]
> reviewed before approved. Two properties are missing in UserSchema. company and job title, hope Ian will update it as soon as he can.

What you mean by two properties are missing in UserSchema???

**Comment by abc-1211** [comment]
> reviewed before approved. Two properties are missing in UserSchema. company and job title, hope Ian will update it as soon as he can.

Job title is within the design discipline as for the company, shall we talk about this tonight during the meeting to ensure where to place it at?

**Comment by meeday** [comment]
Job title needs to be in the userSchema as well because the user inputs that when they register

**Review by meeday — APPROVED** [review]

**Review by meeday — APPROVED** [review]

**Review by meeday — APPROVED** [review]

**Pull request merged**
